### ISSUE TITLE
功能包只能部分编译成功 

### ISSUE THREAD

**Issue by wu1999a** [MiRoboticsLab/cyberdog_ros2#125]
Finished <<< cyberdog_interfaces [1.94s]                                
Starting >>> cyberdog_grpc                                              
--- stderr: cyberdog_devices_base                                       
CMake Error at test/CMakeLists.txt:17 (pluginlib_enable_plugin_testing):
  Unknown CMake command "pluginlib_enable_plugin_testing".

---
Failed   <<< cyberdog_devices_base [6.38s, exited with code 1]
Aborted  <<< cyberdog_grpc [0.27s]
Aborted  <<< behaviortreecppv3_vendor [14.3s]
Aborted  <<< wifirssi [0.45s]
Aborted  <<< motion_plugin_lcm [4.40s]
Aborted  <<< audio_base [21.6s]                                    

Summary: 24 packages finished [34.8s]
  1 package failed: cyberdog_devices_base
  5 packages aborted: audio_base behaviortreecppv3_vendor cyberdog_grpc motion_plugin_lcm wifirssi
  2 packages had stderr output: cyberdog_devices_base xiaoai_sdk_vendor
  16 packages not processed

只有24个包编译成功

**Comment by homalozoa** [comment]
你好，请下载main或已发布版本，devel仅供开发人员使用。
