### ISSUE TITLE
请求提供新版本的线刷镜像

### ISSUE THREAD

**Issue by zbwu** [MiRoboticsLab/cyberdog_ros2#130]
现在只能恢复到82版本再OTA到新版

请求提供新版本的线刷镜像

**Comment by tuyaliang** [comment]
同求

**Comment by zbwu** [comment]
这个项目看来已经在冰箱了

**Comment by mi-CyberDog** [comment]
https://github.com/MiRoboticsLab/cyberdog_ros2/discussions/133，已经更新到discussion讨论区
