### ISSUE TITLE
在控制连链路上有用到实时总线吗

### ISSUE THREAD

**Issue by mailonghua** [MiRoboticsLab/cyberdog_ros2#131]
## Brief modification description
请问有用到实时总线吗？若是没有用到如何确保链路的延迟
## Detailed information

**Comment by mi-CyberDog** [comment]
CAN总线就应该算是实时总线的一种，对电机的控制主要利用CAN总线

**Comment by mailonghua** [comment]
> CAN总线就应该算是实时总线的一种，对电机的控制主要利用CAN总线

解算mr813直接can到电机吗

**Comment by mi-CyberDog** [comment]
MR813没有集成CAN控制器，不支持CAN协议传输，所以我们增加了一个 单片机将SPI的数据转换成CAN

**Comment by mailonghua** [comment]
> MR813没有集成CAN控制器，不支持CAN协议传输，所以我们增加了一个 单片机将SPI的数据转换成CAN

明白了，多谢
