### ISSUE TITLE
Could you provide the urdf file and STEP file for CyberDog?

### ISSUE THREAD

**Issue by ZiwenZhuang** [MiRoboticsLab/cyberdog_ros2#19]
## Brief modification description
providing URDF file for cyberdog

## Detailed information
We wish that by having the urdf file, we can make a simulation interface based on PyBullet. And robot learning research based on cyberdog can be performed

**Comment by zhangsining734** [comment]
附议

**Comment by homalozoa** [comment]
再等等吧，领导不让给。我也没办法...

**Comment by zbwu** [comment]
这个文件对开发很关键，当然也涉及很多产品商业信息。

借这个地方问一下，驱动控制代码和URDF是不是在Cyberdog的开源计划里面？

**Comment by homalozoa** [comment]
> 这个文件对开发很关键，当然也涉及很多产品商业信息。
> 
> 借这个地方问一下，驱动控制代码和URDF是不是在Cyberdog的开源计划里面？
> 

@zbwu 在计划里，只不过还需要等等。

**Comment by tpoisonooo** [comment]
> 再等等吧，领导不让给。我也没办法...

缺主控逻辑好比缺灵魂，硬件不本质啊。不赶紧交给 contributor 瞎折腾，死守这那玩意儿有啥用。

**Comment by a52521255** [comment]
附议附议！不然能做的很有限啊

**Comment by homalozoa** [comment]
> > 这个文件对开发很关键，当然也涉及很多产品商业信息。
> > 借这个地方问一下，驱动控制代码和URDF是不是在Cyberdog的开源计划里面？
> 
> @zbwu 在计划里，只不过还需要等等。

最近又问了下领导，大概率不会开源了……离谱

**Comment by MarkFzp** [comment]
没有urdf就没法做放到仿真环境里，很多科研方向就没法进行，宇树就开源了urdf和运动控制的sdk

**Comment by MarkFzp** [comment]
> > > 这个文件对开发很关键，当然也涉及很多产品商业信息。
> > > 借这个地方问一下，驱动控制代码和URDF是不是在Cyberdog的开源计划里面？
> > 
> > 
> > @zbwu 在计划里，只不过还需要等等。
> 
> 最近又问了下领导，大概率不会开源了……离谱

没有urdf就没法做放到仿真环境里，很多科研方向就没法进行，宇树就开源了urdf和运动控制的sdk

**Comment by ZiwenZhuang** [comment]
有人有高精度扫描仪嘛hhhhh，干脆拆了自己扫描一个，然后标定。。。。

**Comment by MAVProxyUser** [comment]
URDF was ever provided?

**Comment by Yaoying1** [comment]
urdf文件还会开源吗

**Comment by MAVProxyUser** [comment]
The Cyberdog team is dead. All good employees, quit, or do not like their job. I hear the manager of team is awful and does not care about open source @Yaoying1

**Comment by Yaoying1** [comment]
> 

我去一个机器人描述文件而已 没必要死守着吧 这还当个宝了

**Comment by MAVProxyUser** [comment]
Email project manager and complain he does not care about end users that purchased his project. [xiangdiyun@xiaomi.com](mailto:xiangdiyun@xiaomi.com)

**Comment by Yaoying1** [comment]
> 给项目经理发电子邮件，抱怨他不关心购买他项目的最终用户。[xiangdiyun@xiaomi.com](mailto:xiangdiyun@xiaomi.com)

你好 有相关社区或者群来进行讨论、交流吗
