### ISSUE TITLE
手柄控制cyberdog_joy发布的话题（ "body_cmd"）应该加上命名空间

### ISSUE THREAD

**Issue by chengyangkj** [MiRoboticsLab/cyberdog_ros2#30]
Please provide information for your bug report:

- if you're using from source, provide the Git commit hash
  (via `git log -1 --format="%H" | xargs`):
671a95bc3f2a30ac6fd671ce68a61f15e11ef041
- if you're using a release package, provide the version
  (e.g. via `cyberdog_version -a`):

- provide all information that is needed to analyze and reproduce the bug
  (logs, commands that have been used, ...)
cyberdog_joy发布的“body_cmd”话题，需要加上命名空间，否则不会响应手柄动作
  pimpl_->cmd_vel_pub = this->create_publisher<msg_SE3VelocityCMD>(
    "body_cmd",
    rclcpp::SystemDefaultsQoS());

**Comment by homalozoa** [comment]
@chengyangkj  Hi, namespace并不需要在这里输入，所有的namespace都是通过https://github.com/MiRoboticsLab/cyberdog_ros2/blob/devel/cyberdog_bringup/cyberdog_pycommon/launch_tools.py#L44 获取后传入的。
