### ISSUE TITLE
铁蛋的app源码

### ISSUE THREAD

**Issue by mailonghua** [MiRoboticsLab/cyberdog_ros2#35]
## Brief modification description
铁蛋的app源码会有开源的计划吗？谢谢

**Comment by homalozoa** [comment]
Hi @mailonghua ，感谢关注本项目。
app源码因为涉及到一些token和小米内部库的原因，暂时没有开源计划。
如果想尝试用Android/iOS app控制铁蛋，可以直接使用grpc进行控制和信息获取。相关例程可以翻看readme的相关项目。
