### ISSUE TITLE
Where can you buy a robot for $ 1,500?

### ISSUE THREAD

**Issue by amburkoff** [MiRoboticsLab/cyberdog_ros2#46]
Where can i buy a cyberdog for $ 1,500?
After the sale of 1000 pieces, will it still be produced? What are your future plans?
I would like to buy but cannot find where.

**Comment by homalozoa** [comment]
Hi @amburkoff . Thank you for paying attention to CyberDog. But there is no overseas purchase channel for CyberDog. Perhaps we will open this channel in next generation.
