### ISSUE TITLE
隔壁问题提到了next generation

### ISSUE THREAD

**Issue by wojiao42** [MiRoboticsLab/cyberdog_ros2#49]
有点冷清鸭

看隔壁一个兄弟问一千五百刀的铁蛋哪里买，有大佬回复说next generation，请问这个next generation会怎么改进，如何收集意见呢

我相信大部分能拿到铁蛋的用户还是有很多意见想提的，但是个人感觉git不是一个适合国内大部分实际拿到铁蛋用户的社区（似乎开发者并不是主要筛选幸存者），微博上或者微信建立一个官方的讨论群组不好吗

昨天收到了狗，很开心，不知道怎么分享快乐（社区发不出去贴子我服了...），特地来贵宝地感谢一下项目组各位大佬，话说能不能出个钢化膜保护一下铁蛋的眼睛，搞机器人的二次开发磕磕碰碰的也挺心疼的……

**Comment by homalozoa** [comment]
Hi，homalozoa是我的微信，加我就可以
