### ISSUE TITLE
手机与CYBER进行通信使用了GRPC协议，为什么不使用类似ros_bridge的package，这两者之间是如何权衡的

### ISSUE THREAD

**Issue by mailonghua** [MiRoboticsLab/cyberdog_ros2#65]
请教一下
手机与CYBER进行通信使用了GRPC协议，为什么不使用类似ros_bridge的package，这两者之间是如何权衡的
在效率上是有什么区别吗

**Comment by homalozoa** [comment]
Hi 你好 @mailonghua . 我们使用gRPC的原因是因为gRPC支持的语言广泛，适用于各类开发背景的朋友对铁蛋进行控制，相较于使用websockets的ros bridge suite，使用起来更加灵活。
